### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by zBlbz** [MizaGBF/MizaBOT#1] opened 2019-08-10 04:13 UTC
Hi, is there a place where I can dm you? I have some question regarding the bot.

**Comment by MizaGBF** [comment] 2019-08-29 19:20
I'm so sorry, I only noticed your question just now.
If you have a technical question, here is fine (I'll try to pay more attention the next time I pass by).
If it's about an invite link for the bot, it's a no. I only share it to a limited amount of servers.

**Comment by zBlbz** [comment] 2019-08-31 02:18
I'm having some trouble setting it up on my own server.
Heroku:
![image](https://user-images.githubusercontent.com/53961280/64057662-34263280-cbd2-11e9-9aca-27df77868b45.png)

Example folder/ config.json
![image](https://user-images.githubusercontent.com/53961280/64057699-cfb7a300-cbd2-11e9-8393-c4f4b1c1eea6.png)

Example folder/ settings.yaml (do I use google client ID and secret? or discord?)
![image](https://user-images.githubusercontent.com/53961280/64057721-2c1ac280-cbd3-11e9-9abf-d7842e434c45.png)

Example folder/ credentials.json
![image](https://user-images.githubusercontent.com/53961280/64057788-f924fe80-cbd3-11e9-8d75-1913c2bad0b8.png)
Download JSON > rename it to credentials.json > place it on example folder?

Example folder/ save.json
Did not touch it as I have no idea what I should be adding on save.json.

I did pip install -r requirements.txt on my pc and heroku > run console.

Do I drag everything in the example folder to the root folder?

**Comment by MizaGBF** [comment] 2019-09-09 09:12
sorry for the late reply again.
the problem is in your config file, line 3.
put your discord key between quotes.
```
"tokens" : {
    "discord" : "...discord token...",
    "drive" : "....drive key..."
},
```

**Comment by MizaGBF** [comment] 2019-09-09 09:15
To add more to that: a loadConfig() error in heroku is usually caused by a malformed config.json (quote, bracket or comma missing)

**Comment by zBlbz** [comment] 2019-09-10 13:13
![image](https://user-images.githubusercontent.com/53961280/64614051-34140700-d40a-11e9-95d1-fa6e5556c0b1.png)

Now there's a different error after adding quotes to the discord and drive tokens. I guess its my google drive token issue as i'm unsure where to find/ create it.

**Comment by zBlbz** [comment] 2019-09-10 15:10
![image](https://user-images.githubusercontent.com/53961280/64626063-cc68b680-d41f-11e9-8963-b9c6294aaee6.png)

I got my drive token from OAuth 2.0 Playground

**Comment by MizaGBF** [comment] 2019-09-14 07:30
I'm not sure, to be honest.
I haven't used this system to get my google token.
Did you generate your credentials.json first?

I ran something like:
`from pydrive.auth import GoogleAuth

gauth = GoogleAuth()
gauth.LocalWebserverAuth()
gauth.SaveCredentialsFile("credentials.json")`
locally to get it. It will let you authentificate in a web browser, once.

If you did, I think that the problem is somewhere else.

**Comment by zBlbz** [comment] 2019-09-14 16:05
Heroku:
![image](https://user-images.githubusercontent.com/53961280/64910643-1668d980-d74b-11e9-8ae3-d03de8542884.png)

googleapis link from heroku:
![image](https://user-images.githubusercontent.com/53961280/64910647-1e287e00-d74b-11e9-9d39-550c560fbab6.png)

console.developers.google:
![image](https://user-images.githubusercontent.com/53961280/64910692-d0f8dc00-d74b-11e9-84c0-3bfec6ef92eb.png)

After generating credentials.json from the python file, console.developers.google finally manage to receive something but there's still some error.

**Comment by MizaGBF** [comment] 2019-09-17 14:07
Did you put the example save.json file in the folder? The bot doesn't generate one the first time.
I'm not sure what's the problem, otherwise.

**Comment by zBlbz** [comment] 2019-09-17 14:45
![image](https://user-images.githubusercontent.com/53961280/65051942-65f21400-d99c-11e9-9175-4d52f2037ff3.png)
Yes, save.json is in the folder. Am I suppose to edit the save.json for it to work?

**Comment by MizaGBF** [comment] 2019-09-20 14:41
I mean, in the google drive folder where the bot will save.
It seems to fail at retrieving the save.
No you don't have to edit it, I believe it should work fine.

**Comment by zBlbz** [comment] 2019-09-21 10:30
After placing the save.json to my google drive, the problem still persists.
I tried using the sample code from pydrive and it's able to return the save.json id.
```
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive

gauth = GoogleAuth()
gauth.LocalWebserverAuth() # Creates local webserver and auto handles authentication.

drive = GoogleDrive(gauth)

# Auto-iterate through all files that matches this query
file_list = drive.ListFile({'q': "'root' in parents and trashed=false"}).GetList()
for file1 in file_list:
  print('title: %s, id: %s' % (file1['title'], file1['id']))
```
![image](https://user-images.githubusercontent.com/53961280/65372007-bb7c3880-dc9c-11e9-831d-14a832c69581.png)

**Comment by MizaGBF** [comment] 2019-09-25 16:58
Check this:
My google application uses these scopes:
```../auth/drive.appdata
../auth/drive.file```
I see this at [https://console.developers.google.com/apis/credentials](https://console.developers.google.com/apis/credentials) > `OAuth consent screen`

**Comment by zBlbz** [comment] 2019-09-26 15:41
Ok I have added the 2 scope you mention, still having the same error.

Here's all my settings related to google, not sure where did I do wrong.

Google Drive API: 
![image](https://user-images.githubusercontent.com/53961280/65701890-aea08000-e0b4-11e9-971c-ad4172b1fb2f.png)

OAuth 2.0 Client web application:
![image](https://user-images.githubusercontent.com/53961280/65702372-7483ae00-e0b5-11e9-93c2-9665fb9d86c9.png)

OAuth consent screen:
![image](https://user-images.githubusercontent.com/53961280/65702497-b3b1ff00-e0b5-11e9-907b-8daff96e4c71.png)

Config and settings:
![image](https://user-images.githubusercontent.com/53961280/65703137-ced13e80-e0b6-11e9-9a8a-0cb5657d93b5.png)

**Comment by zBlbz** [comment] 2019-09-26 15:45
Ok I have added the 2 scope you mention, still having the same error.

Here's all my settings related to google, not sure where did I do wrong.

Google Drive API: 
![image](https://user-images.githubusercontent.com/53961280/65701890-aea08000-e0b4-11e9-971c-ad4172b1fb2f.png)

OAuth 2.0 Client web application:
![image](https://user-images.githubusercontent.com/53961280/65702372-7483ae00-e0b5-11e9-93c2-9665fb9d86c9.png)

OAuth consent screen:
![image](https://user-images.githubusercontent.com/53961280/65702497-b3b1ff00-e0b5-11e9-907b-8daff96e4c71.png)

Config and settings:
![image](https://user-images.githubusercontent.com/53961280/65703562-8c5c3180-e0b7-11e9-925f-cbee903d09a6.png)

**Comment by MizaGBF** [comment] 2019-09-28 12:11
It took me a while to check (Google UI is terrible to navigate in).  
I'm lacking the Drive UI Integration tab (on the first screenshot) but everything else looks the same.  
I think your problem is with  `config.json > tokens > drive`, the name is misleading (I'm sorry) but you are supposed to put the drive folder id here, not your access token (the token is already read from the credentials file).
Go to the drive folder in your browser. The url should be something like `https://drive.google.com/drive/folders/<id>`. This id is what you are supposed to put in config.json.

**Comment by zBlbz** [comment] 2019-09-28 16:42
Alright now it able get the save.json file but with a different error.

![image](https://user-images.githubusercontent.com/53961280/65819600-1d1a4500-e251-11e9-8e27-b738c423a07e.png)

As for the config.json, will it cause any problem if I were to put 0 for the "ids" since I do not have most of the channel.

**Comment by MizaGBF** [comment] 2019-10-03 10:54
0 should work. Some commands might crash or do nothing as a result. Some tasks might cause problems, I might try to update them.
As for the save error, check at the specified line.

**Comment by zBlbz** [comment] 2019-10-03 12:41
Alright I think its working now.

Discord:
![image](https://user-images.githubusercontent.com/53961280/66127058-756c9080-e61d-11e9-9059-fbbb3817a874.png)
![image](https://user-images.githubusercontent.com/53961280/66127334-f4fa5f80-e61d-11e9-930c-b49d274949d2.png)

Heroku:
![image](https://user-images.githubusercontent.com/53961280/66127249-ced4bf80-e61d-11e9-9baa-7c5dde2d44c1.png)

How do I unblock the bot?

**Comment by MizaGBF** [comment] 2019-10-14 09:59
For the help issue, one of your discord setting is preventing it to dm you (check in setting > privacy or something similar). I don't know if adding the bot as a friend would work.

For the other errors, try the latest version, I added some extra checks to avoid them. If you know python, it might be better to edit out some things yourself.
The react error will you to add your own emote ids in config.json.

**Comment by zBlbz** [comment] 2019-10-17 14:07
Thanks the $help is working now but there's still some error.

![image](https://user-images.githubusercontent.com/53961280/67014698-d9b44780-f127-11e9-9c32-d0dd08bd4263.png)
![image](https://user-images.githubusercontent.com/53961280/67014735-e89afa00-f127-11e9-87e2-c84f3bb81420.png)

Where do I get refresh_token/ access_type to offline? The error happen after > 11hrs online.

**Comment by MizaGBF** [comment] 2019-10-21 13:47
I believe that your `credentials.json` file is the problem, it hasn't be generated properly and end up expiring after a certain amount of time.
Make a folder somewhere on your computer with:
- `client_secrets.json` from the google drive api credentials page.
- a copy of your `settings.yaml` file.
- a new file (name it whatever.py) and put inside:
```python
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive   
gauth = GoogleAuth()
gauth.LocalWebserverAuth()
gauth.LoadCredentialsFile(gauth)
```
(if you didn't install pydrive, run a `pip install pydrive` in a prompt, before).
Run this python file, your internet browser should open to authorize the app.
Once it's done, a new `credentials.json` file should be in the folder. Use that one.

If it doesn't work, I have no ideas why.

**Comment by zBlbz** [comment] 2019-10-26 02:58
Thanks its able to run 24/7 now!
For the save.json:
Do I have to manually update in the "schedule"?

**Comment by MizaGBF** [comment] 2019-10-31 12:13
Yes the `$schedule` command is manually updated with `$setschedule`, I don't have a way to automate it.
I'm closing the issue, since everything is resolved. Should be a nice "help" if someone stumbles upon it.

**Closed by MizaGBF** 2019-10-31 12:13 UTC
Labels: question
