### ISSUE TITLE
loadData error when deploying

### ISSUE THREAD

**Issue by atliv** [MizaGBF/MizaBOT#18] opened 2022-05-28 14:08 UTC
hello i have a lil problem again, it's seems when i tried to up the bot in local or production env. i got this error

![image](https://user-images.githubusercontent.com/10157718/170828838-f041ba5e-852b-42c7-8404-2f291fdcf6d9.png)

and here's my config.json 

![image](https://user-images.githubusercontent.com/10157718/170828941-12102cc3-861d-44eb-8995-9dd4fea3a9ad.png)

is my config file setup is correct ady or something wrong in somewhere else ?

**Comment by MizaGBF** [comment] 2022-05-28 14:27
it's a save.json error, not config.json.  
Again it's caused by old code which I didn't test properly with the example file (or broke at some point).  
I just pushed a fix, try it out.

**Comment by atliv** [comment] 2022-05-28 15:01
here i get new error message now 
![image](https://user-images.githubusercontent.com/10157718/170831004-d3cd1e6a-9857-45c1-a881-e836647e399e.png)

**Comment by MizaGBF** [comment] 2022-05-28 15:06
The first two are normal, it's because my test files are missing (the bot will run without them).  
The third, however, I'm not sure. What python version are you running?

**Comment by atliv** [comment] 2022-05-28 15:13
it's 3.10.4 
![image](https://user-images.githubusercontent.com/10157718/170831364-7a1fe858-bf97-4ef4-9605-c7b054844317.png)

**Comment by MizaGBF** [comment] 2022-05-28 15:14
I found the cause of the problem, it's likely caused by Windows.
I'll push a fix in a few minutes.

**Comment by atliv** [comment] 2022-05-28 15:26
btw i just want to give you some update, the bot is online in my dummy server but it didnt response everytime i  typed a command, here's  the log in my heroku 
![image](https://user-images.githubusercontent.com/10157718/170831911-4f29d6ab-0494-4dbf-86ff-80ab000771f6.png)

**Comment by MizaGBF** [comment] 2022-05-28 15:41
From what I see:
- The missing access error is caused by a permission problem. Double check its permissions in your server.  
If it's not it, check the invite link you used: It needs the applications.commands scope.  
The url should have something like `&scope=bot%20applications.commands`.  
Also, take note the commands can take up to one hour to be available in your server (it's a Discord side problem, there is nothing we can do about it).  
- The two Invalid key errors are caused by config.json, image_upload and debug_update channel IDs aren't set or wrong (You can ignore it for now).  
- The last two errors are because it couldn't access the debug channel you set in config.json. Considering it didn't cause a key error above, maybe a permission problem too?

**Comment by MizaGBF** [comment] 2022-05-28 15:49
In doubt: Also check if you put your server ID under `debug_server`.

**Comment by atliv** [comment] 2022-05-28 15:52
> 

yeah i forgot to check application commands. now in my server the bot will response "the application did not respond"
![image](https://user-images.githubusercontent.com/10157718/170832869-412dbeb1-2e54-4d81-a022-f7c364ed3379.png)
is this what you mean "the commands can take up to one hour to be available" ?

**Comment by MizaGBF** [comment] 2022-05-28 15:56
If you can see the commands when typing `/`, then they are already available (it doesn't take long with only one server).  
I believe you get this message because the bot can't post in this channel, or something similar.

**Comment by MizaGBF** [comment] 2022-05-28 15:57
Note: you should see a boot message, if everything is alright, in your debug channel. Something like this:
![image](https://user-images.githubusercontent.com/47531574/170833076-46a53032-f6e7-4079-845c-d73560181a98.png)

**Comment by atliv** [comment] 2022-05-28 15:59
ok thanks, i think i will try to check the permission in my server first. about loadData error has been solved, 

should i close this issue ?

**Comment by MizaGBF** [comment] 2022-05-28 15:59
If there is nothing else, yes.

**Closed** 2022-05-28 15:59 UTC
